### PR TITLE
Improved button vertical alignment

### PR DESCRIPTION
**Pull request by davidwlewis**
The window buttons tend to hang a couple of pixels away from the top edge of the screen. Other themes might need adjusting, I just use default.

### CODE REVIEW

**Comment by franglais125** [comment]
Thanks a lot for your contribution!

I'm having a hard time seeing the improvement (at least in my testing). Could you provide a screenshot of the "before/after" look?

In my testing, the default look is vertically centered. With the patch, everything is stuck to the top of the panel. This could, however, look different for you, hence why I'd like to see your case :)

Again, thanks for looking into this!

**Comment by davidwlewis** [comment]
The problem is that a row or two of pixels above the buttons aren't clickable. After the change, in my setup there is no discernible visual difference:

before2
after2

But the top 2 rows of pixels are clickable - so I can just mouse to the corner of the screen and not have to nudge down a little. For whatever reason just changing the css to make the buttons slightly taller wasn't enough, they still sat a pixel or two away from the edge.

If this breaks setups with taller top bars, perhaps it should be configurable, or I can see if I can find a way to make the clickable area of the button span the vertical space.

**Comment by franglais125** [comment]
> But the top 2 rows of pixels are clickable - so I can just mouse to the corner of the screen and not have to nudge down a little. For whatever reason just changing the css to make the buttons slightly taller wasn't enough, they still sat a pixel or two away from the edge.

Ah, I see! Thanks, I didn't think about the clickable area, I was more focusing on the aesthetics. I'll take another look soon. Cheers

**Comment by bmhm** [comment]
:+1: looking forward to integration!

**Comment by franglais125** [comment]
I'll assume this has been completed. We can re-open if necessary. Cheers and thanks for your contribution!

**Pull request closed without merging**
