### PR TITLE
Fix suru icon color

### PR DESCRIPTION
**Pull request by Feichtmeier**
@franglais125 sorry for the mistake, now with the correct color!

Use white for minimize, maximize, close, restore buttons 
For Yaru, Suru, Communitheme icon theme
All three themes are needed due to a name change for the communitheme snap and the new theme name for ubuntu 18.10

image

### CODE REVIEW

**Comment by franglais125** [comment]
Merged as [7e1493447bb7d824bb397f9490107f35847840f6]. Thanks again!

**Comment by Feichtmeier** [comment]
@franglais125 great thank you! Why did you close it and not merge it? :D maybe I lack some understanding here (really, no irony or something)

**Comment by franglais125** [comment]
I cherry-picked your new commit locally with git (not through github). When I pushed the changes, your code was already in and there was no need to merge this PR.

I often work more locally than through this interface!

**Comment by Feichtmeier** [comment]
Ah thanks for clarification =) Best regards

**Pull request closed without merging**
