### PR TITLE
Add support for Suru, Yaru and Communitheme Icon Themes

### PR DESCRIPTION
**Pull request by Feichtmeier**
All three icon themes are the Suru icon theme, but to have support for 
all versions of the Communitheme installation there should be packages 
for all three.

Yaru/Communitheme will be the default icon theme for Ubuntu 18.10 and is installable right now with the communitheme snap in 18.04.

### CODE REVIEW

**Comment by Feichtmeier** [comment]
@franglais125 Hi there - do you have currently time to review this PR? :smiley: 
Best regards, Frederik

**Comment by franglais125** [comment]
Thanks a lot for this, and sorry for the delay! It truly appreciated :)

**Comment by Feichtmeier** [comment]
You are welcome! I'm a user of your extension since many months and wanted to give something back!
I hope everything is correct on this commit?

**Comment by Feichtmeier** [comment]
Ah, sorry, I missed to update the color in the commit!
Fix incoming!

**Pull request merged**
